WhisperLarge:

  nome: Whisper Large V3 Q4.0
  path: C:\Users\Admin\Desktop\models\ASR Models\Whisper\Whisper-large-v3 4Bit
  hf: https://huggingface.co/openai/whisper-large-v3

#################################

CPU_CONFIG:

  Gemma 9B Q4:
    path: C:\Users\Admin\Desktop\models\Language Models\CPU\Gemma 9B Q4\gemma-2-9b-it-Q4_K_S.gguf
    hf: https://huggingface.co/google/gemma-2-9b
    params: 9B
    hardware: CPU

  Hermes Llama 8B Q4:
    path: C:\Users\Admin\Desktop\models\Language Models\CPU\Hermes Llama 8B Q4\Hermes Llama 8B Q4.gguf
    hf: https://huggingface.co/NousResearch/Hermes-3-Llama-3.1-8B-GGUF
    params: 8B
    hardware: CPU

  Kimi 16B Q4:
    path: C:\Users\Admin\Desktop\models\Language Models\CPU\Kimi 16B Q4\Moonlight-16B-A3B-Instruct-Q4_K_S.gguf
    hf: https://huggingface.co/moonshotai/Moonlight-16B-A3B-Instruct
    params: 16B
    hardware: CPU

  Microsoft Phi 4B Q4:
    path: C:\Users\Admin\Desktop\models\Language Models\CPU\Microsoft Phi 4B Q4\Microsoft Phi 4B Q4.gguf
    hf: https://huggingface.co/microsoft/phi-4
    params: 4B
    hardware: CPU

  Mistral 7B Q4:
    path: C:\Users\Admin\Desktop\models\Language Models\CPU\Mistral 7B Q4\Mistral 7B Q4.gguf
    hf: https://huggingface.co/mistralai/Mistral-7B-Instruct-v0.2
    params: 7B
    hardware: CPU

  Nvidia Nemotron 4B Q4:
    path: C:\Users\Admin\Desktop\models\Language Models\CPU\Nvidia Nemotron 4B Q4\NVIDIA-Nemotron-3-Nano-4B-Q4_K_S.gguf
    hf: https://huggingface.co/nvidia/NVIDIA-Nemotron-3-Nano-4B-GGUF
    params: 4B
    hardware: CPU

  Qwen 8B Q4:
    path: C:\Users\Admin\Desktop\models\Language Models\CPU\Qwen 8B Q4\Qwen 8B Q4.gguf
    hf: https://huggingface.co/Qwen/Qwen3-8B-GGUF
    params: 8B
    hardware: CPU

##################################

GPU_CONFIG:

  llama.cpp:

    #GLM 31B Q2:
      #path: C:\Users\Admin\Desktop\models\Language Models\GPU\llama.cpp\GLM 31B Q2\GLM-4.7-Flash-UD-IQ2_M.gguf
      #hf: https://huggingface.co/zai-org/GLM-4.7-Flash
      #params: 31B
      #hardware: GPU

    GPT OSS 20B Q4:
      path: C:\Users\Admin\Desktop\models\Language Models\GPU\llama.cpp\GPT OSS 20B Q4\gpt-oss-20b-Q4_K_S.gguf
      hf: https://huggingface.co/openai/gpt-oss-20b
      params: 20B
      hardware: GPU

    IBM Granite 30B Q2:
      path: C:\Users\Admin\Desktop\models\Language Models\GPU\llama.cpp\IBM Granite 30B Q2\granite-4.1-30b-Q2_K.gguf
      hf: https://huggingface.co/ibm-granite/granite-4.2-30b
      params: 30B
      hardware: GPU

    Microsoft Phi 15B Q4:
      path: C:\Users\Admin\Desktop\models\Language Models\GPU\llama.cpp\Microsoft Phi 15B Q4\phi-4-Q4_K_M.gguf
      hf: https://huggingface.co/microsoft/phi-4
      params: 15B
      hardware: GPU

    #Qwen 30B Q2:
      #path: C:\Users\Admin\Desktop\models\Language Models\GPU\llama.cpp\Qwen 30B Q2\Qwen_Qwen3-30B-A3B-IQ2_S.gguf
      #hf: https://huggingface.co/Qwen/Qwen3-30B-A3B
      #params: 30B
      #hardware: GPU
