[project]
name = "a-three-dimensional-analysis-for-llm-deployment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=1.15.0",
    "bitsandbytes>=0.50.2",
    "datasets>=2.19.1",
    "humanize>=4.16.0",
    "ipykernel>=7.3.0",
    "llmcompressor>=0.6.0.1",
    "lm-eval>=0.4.13",
    "protobuf>=7.36.1",
    "sentencepiece>=0.2.2",
    "torch>=2.14.0",
    "torchvision>=0.29.0",
    "transformers>=4.52.4",
]

[tool.uv.sources]
torchvision = { index = "pytorch" }

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu126"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true
