MODELS:

  QWEN 2.5 0.5B:
    path: C:\Users\Admin\Desktop\models\Language Models\Qwen 2.5 0.5B
    inference: llama.cpp
    context: 2080
    ngl: 0
    device: cpu

  Microsoft Phi 3.5 Q4.0:
    path: C:\Users\Admin\Desktop\models\Language Models\Microsoft Phi 3.5 Q4
    inference: llama.cpp
    context: 2080
    ngl: 0
    device: cpu

  Bonsai 27B Q1.0:
    path: C:\Users\Admin\Desktop\models\Language Models\Bonsai 27B Q1.0
    inference: llama.cpp
    context: 2080
    ngl: 0
    device: cpu

  Mistral 7B Q4.0:
    path: C:\Users\Admin\Desktop\models\Language Models\Mistral 7B Q4
    inference: transformers
    device: cuda

  Microsoft Phi 4 Q4.0:
    path: C:\Users\Admin\Desktop\models\Language Models\Microsoft Phi 4 Q4
    inference: transformers
    device: cuda

  Amália 9B DPO Q8:
    path: C:\Users\Admin\Desktop\models\Language Models\Amália 9B DPO Q8
    inference: transformers
    device: cuda
